package com.bean;

import java.util.Date;

public class Role {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column smbms_role.id
     *
     * @mbggenerated Mon Aug 28 08:34:13 CST 2017
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column smbms_role.roleCode
     *
     * @mbggenerated Mon Aug 28 08:34:13 CST 2017
     */
    private String roleCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column smbms_role.roleName
     *
     * @mbggenerated Mon Aug 28 08:34:13 CST 2017
     */
    private String roleName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column smbms_role.createdBy
     *
     * @mbggenerated Mon Aug 28 08:34:13 CST 2017
     */
    private Long createdBy;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column smbms_role.creationDate
     *
     * @mbggenerated Mon Aug 28 08:34:13 CST 2017
     */
    private Date creationDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column smbms_role.modifyBy
     *
     * @mbggenerated Mon Aug 28 08:34:13 CST 2017
     */
    private Long modifyBy;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column smbms_role.modifyDate
     *
     * @mbggenerated Mon Aug 28 08:34:13 CST 2017
     */
    private Date modifyDate;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column smbms_role.id
     *
     * @return the value of smbms_role.id
     *
     * @mbggenerated Mon Aug 28 08:34:13 CST 2017
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column smbms_role.id
     *
     * @param id the value for smbms_role.id
     *
     * @mbggenerated Mon Aug 28 08:34:13 CST 2017
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column smbms_role.roleCode
     *
     * @return the value of smbms_role.roleCode
     *
     * @mbggenerated Mon Aug 28 08:34:13 CST 2017
     */
    public String getRoleCode() {
        return roleCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column smbms_role.roleCode
     *
     * @param roleCode the value for smbms_role.roleCode
     *
     * @mbggenerated Mon Aug 28 08:34:13 CST 2017
     */
    public void setRoleCode(String roleCode) {
        this.roleCode = roleCode == null ? null : roleCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column smbms_role.roleName
     *
     * @return the value of smbms_role.roleName
     *
     * @mbggenerated Mon Aug 28 08:34:13 CST 2017
     */
    public String getRoleName() {
        return roleName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column smbms_role.roleName
     *
     * @param roleName the value for smbms_role.roleName
     *
     * @mbggenerated Mon Aug 28 08:34:13 CST 2017
     */
    public void setRoleName(String roleName) {
        this.roleName = roleName == null ? null : roleName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column smbms_role.createdBy
     *
     * @return the value of smbms_role.createdBy
     *
     * @mbggenerated Mon Aug 28 08:34:13 CST 2017
     */
    public Long getCreatedBy() {
        return createdBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column smbms_role.createdBy
     *
     * @param createdBy the value for smbms_role.createdBy
     *
     * @mbggenerated Mon Aug 28 08:34:13 CST 2017
     */
    public void setCreatedBy(Long createdBy) {
        this.createdBy = createdBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column smbms_role.creationDate
     *
     * @return the value of smbms_role.creationDate
     *
     * @mbggenerated Mon Aug 28 08:34:13 CST 2017
     */
    public Date getCreationDate() {
        return creationDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column smbms_role.creationDate
     *
     * @param creationDate the value for smbms_role.creationDate
     *
     * @mbggenerated Mon Aug 28 08:34:13 CST 2017
     */
    public void setCreationDate(Date creationDate) {
        this.creationDate = creationDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column smbms_role.modifyBy
     *
     * @return the value of smbms_role.modifyBy
     *
     * @mbggenerated Mon Aug 28 08:34:13 CST 2017
     */
    public Long getModifyBy() {
        return modifyBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column smbms_role.modifyBy
     *
     * @param modifyBy the value for smbms_role.modifyBy
     *
     * @mbggenerated Mon Aug 28 08:34:13 CST 2017
     */
    public void setModifyBy(Long modifyBy) {
        this.modifyBy = modifyBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column smbms_role.modifyDate
     *
     * @return the value of smbms_role.modifyDate
     *
     * @mbggenerated Mon Aug 28 08:34:13 CST 2017
     */
    public Date getModifyDate() {
        return modifyDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column smbms_role.modifyDate
     *
     * @param modifyDate the value for smbms_role.modifyDate
     *
     * @mbggenerated Mon Aug 28 08:34:13 CST 2017
     */
    public void setModifyDate(Date modifyDate) {
        this.modifyDate = modifyDate;
    }
}