package com.dao;

import com.bean.Address;

public interface AddressMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table smbms_address
     *
     * @mbggenerated Mon Aug 28 08:34:13 CST 2017
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table smbms_address
     *
     * @mbggenerated Mon Aug 28 08:34:13 CST 2017
     */
    int insert(Address record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table smbms_address
     *
     * @mbggenerated Mon Aug 28 08:34:13 CST 2017
     */
    int insertSelective(Address record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table smbms_address
     *
     * @mbggenerated Mon Aug 28 08:34:13 CST 2017
     */
    Address selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table smbms_address
     *
     * @mbggenerated Mon Aug 28 08:34:13 CST 2017
     */
    int updateByPrimaryKeySelective(Address record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table smbms_address
     *
     * @mbggenerated Mon Aug 28 08:34:13 CST 2017
     */
    int updateByPrimaryKey(Address record);
}