package com.dao;

import com.bean.Role;

public interface RoleMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table smbms_role
     *
     * @mbggenerated Mon Aug 28 08:34:13 CST 2017
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table smbms_role
     *
     * @mbggenerated Mon Aug 28 08:34:13 CST 2017
     */
    int insert(Role record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table smbms_role
     *
     * @mbggenerated Mon Aug 28 08:34:13 CST 2017
     */
    int insertSelective(Role record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table smbms_role
     *
     * @mbggenerated Mon Aug 28 08:34:13 CST 2017
     */
    Role selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table smbms_role
     *
     * @mbggenerated Mon Aug 28 08:34:13 CST 2017
     */
    int updateByPrimaryKeySelective(Role record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table smbms_role
     *
     * @mbggenerated Mon Aug 28 08:34:13 CST 2017
     */
    int updateByPrimaryKey(Role record);
}